import type { Metadata } from "next";
import { Badge, SiteFooter, SiteHeader } from "@/components/brand";
import type { WorkflowPayload } from "@/lib/workflowPayload";

const title = "Webhook Documentation | Opportunity Scanner";
const description =
  "Connect Opportunity Scanner to Zapier, Make, n8n, or a custom HTTPS endpoint with the current webhook payload schema and setup recipes.";

export const metadata: Metadata = {
  title: "Webhook Documentation",
  description,
  alternates: { canonical: "/docs/webhooks" },
  openGraph: {
    title,
    description,
    url: "/docs/webhooks",
    siteName: "Opportunity Scanner",
    type: "website",
    images: [
      {
        url: "https://www.opportunityscanner.ai/opportunity-scanner-social-banner.png",
        width: 1200,
        height: 630,
        alt: "Opportunity Scanner webhook documentation"
      }
    ]
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: ["https://www.opportunityscanner.ai/opportunity-scanner-social-banner.png"]
  }
};

type FieldRow = {
  name: keyof WorkflowPayload;
  type: string;
  delivery: "Required" | "Conditional" | "Optional";
  description: string;
};

const fields: FieldRow[] = [
  { name: "scanId", type: "string", delivery: "Required", description: "ID of the scan that produced the opportunity." },
  { name: "opportunityId", type: "string", delivery: "Required", description: "ID of the opportunity within the scan." },
  { name: "opportunity", type: "string", delivery: "Required", description: "Human-readable opportunity headline." },
  { name: "targetOrganization", type: "string", delivery: "Conditional", description: "Agency, buyer, recipient, partner, or other organization to pursue. At least this field or targetAccount is required." },
  { name: "targetAccount", type: "string", delivery: "Conditional", description: "CRM-oriented alias for the target organization. At least this field or targetOrganization is required." },
  { name: "source", type: "string", delivery: "Required", description: "Name of the public source behind the signal." },
  { name: "signalType", type: "string", delivery: "Optional", description: "Display label for the source category, such as Active procurement or Funded buyer." },
  { name: "opportunityType", type: "string", delivery: "Optional", description: "Estimated commercial opportunity classification." },
  { name: "buyerPartnerType", type: "string", delivery: "Optional", description: "Classification of the likely buyer, recipient, partner, or channel target." },
  { name: "revenueMotion", type: "string", delivery: "Required", description: "Recommended route to revenue, such as Sell to Agency, Direct Apply, or Partner with Recipient." },
  { name: "actionability", type: "string", delivery: "Optional", description: "Actionability label: High Actionability, Medium Actionability, or Low Actionability." },
  { name: "actionabilityScore", type: "number", delivery: "Optional", description: "Numeric actionability score generated by Opportunity Scanner." },
  { name: "contactPath", type: "string", delivery: "Optional", description: "Human-readable label for the recommended route to the right office or person." },
  { name: "contactStrategy", type: "string", delivery: "Required", description: "Machine-friendly contact strategy used to route the opportunity." },
  { name: "recommendedContactRoles", type: "string[]", delivery: "Optional", description: "Recommended job functions or roles to locate." },
  { name: "nextStep", type: "string", delivery: "Optional", description: "Human-readable next step. Currently mirrors nextBestAction." },
  { name: "nextBestAction", type: "string", delivery: "Required", description: "The recommended immediate action for the opportunity owner." },
  { name: "manualResearchInstruction", type: "string", delivery: "Optional", description: "Specific research instruction when more qualification is useful." },
  { name: "crmNote", type: "string", delivery: "Required", description: "Context formatted for a CRM note or account activity." },
  { name: "outreachAngle", type: "string", delivery: "Optional", description: "Suggested source-backed angle for outreach or internal positioning." },
  { name: "followUpTask", type: "string", delivery: "Optional", description: "Suggested follow-up task for the opportunity owner." },
  { name: "timeSensitivity", type: "string", delivery: "Optional", description: "Timing classification generated from the source and pursuit context." },
  { name: "pursuitDifficulty", type: "string", delivery: "Optional", description: "Estimated difficulty of pursuing the opportunity." },
  { name: "workflowPayloadReady", type: "boolean", delivery: "Required", description: "Always true for a delivered webhook. Opportunities that are not ready are rejected before delivery." },
  { name: "workflowPayloadReason", type: "string", delivery: "Required", description: "Explanation of why the opportunity is ready for workflow or what must be checked first." },
  { name: "sourceStatus", type: "string", delivery: "Optional", description: "Current status classification for the source record." },
  { name: "sourceDeadline", type: "string", delivery: "Optional", description: "Deadline as represented by the source analysis. Treat as text and verify against the live source." },
  { name: "sourceEvidence", type: "string", delivery: "Required", description: "Evidence summary grounded in the public source record." },
  { name: "sourceUrl", type: "string", delivery: "Optional", description: "Public source URL. Included when a full-report opportunity is sent." }
];

const samplePayload = `{
  "product": "Opportunity Scanner",
  "sent_at": "2026-07-12T15:42:18.214Z",
  "opportunity": {
    "scanId": "scan_01JZ8Y3QF2",
    "opportunityId": "opp_01JZ8Y8K9M",
    "opportunity": "County behavioral health services procurement",
    "targetOrganization": "Example County Health Department",
    "targetAccount": "Example County Health Department",
    "source": "SAM.gov",
    "signalType": "Active procurement",
    "opportunityType": "Agency procurement",
    "buyerPartnerType": "Public agency",
    "revenueMotion": "Sell to Agency",
    "actionability": "High Actionability",
    "actionabilityScore": 86,
    "contactPath": "Procurement office",
    "contactStrategy": "procurement_office",
    "recommendedContactRoles": ["Contracting officer", "Program manager"],
    "nextStep": "Review the notice and confirm response requirements.",
    "nextBestAction": "Review the notice and confirm response requirements.",
    "manualResearchInstruction": "Confirm the incumbent and submission method.",
    "crmNote": "Example County has an active behavioral health procurement...",
    "outreachAngle": "Connect the service to the county's stated access goal.",
    "followUpTask": "Assign an owner to review the source record today.",
    "timeSensitivity": "Immediate",
    "pursuitDifficulty": "Medium",
    "workflowPayloadReady": true,
    "workflowPayloadReason": "Source and next action are specific enough to route.",
    "sourceStatus": "Active",
    "sourceDeadline": "2026-08-14",
    "sourceEvidence": "The notice requests qualified behavioral health providers...",
    "sourceUrl": "https://sam.gov/opp/example"
  }
}`;

const recipes = [
  {
    name: "Zapier",
    purpose: "Create or update a CRM record and assign a follow-up task.",
    steps: [
      "Create a Zap with Webhooks by Zapier as the trigger and choose Catch Hook.",
      "Copy the HTTPS hook URL. In a full Opportunity Scanner report, choose Send to Workflow on a workflow-ready row, paste the URL, and send the opportunity.",
      "In Zapier, test the trigger and confirm that product, sent_at, and the nested opportunity object appear.",
      "Add your CRM action. Map opportunity.targetAccount to the company or account, opportunity.opportunity to the deal name, opportunity.crmNote to notes, and opportunity.sourceUrl to the source-link field.",
      "Add a task action using opportunity.nextBestAction as the task title. Use opportunity.sourceDeadline only after checking that the destination accepts its text format.",
      "Turn on the Zap, then send a second opportunity to verify the live path."
    ],
    mapping: [
      ["Account / company", "opportunity.targetAccount"],
      ["Deal / opportunity name", "opportunity.opportunity"],
      ["Pipeline or motion", "opportunity.revenueMotion"],
      ["Notes", "opportunity.crmNote"],
      ["Task", "opportunity.nextBestAction"],
      ["Source URL", "opportunity.sourceUrl"]
    ]
  },
  {
    name: "Make",
    purpose: "Add a qualified row to Airtable, a CRM, or a shared opportunity table.",
    steps: [
      "Create a scenario and add Webhooks > Custom webhook as the first module.",
      "Create the webhook, copy its HTTPS address, and leave Make waiting for a sample.",
      "Send a workflow-ready opportunity from the full report to that address. Make will infer the nested opportunity fields from the sample.",
      "Add the destination module. Map the target, headline, evidence, motion, contact strategy, next action, and source URL into separate fields.",
      "Add a filter after the webhook if needed: opportunity.workflowPayloadReady equals true. Delivered Opportunity Scanner webhooks already satisfy this rule, but the filter documents the scenario's expectation.",
      "Run once with another row, inspect the created record, then schedule or activate the scenario."
    ],
    mapping: [
      ["Target", "opportunity.targetOrganization"],
      ["Signal", "opportunity.opportunity"],
      ["Evidence", "opportunity.sourceEvidence"],
      ["Contact route", "opportunity.contactPath"],
      ["Owner action", "opportunity.nextBestAction"],
      ["Source status", "opportunity.sourceStatus"]
    ]
  },
  {
    name: "n8n",
    purpose: "Route opportunities by revenue motion and create an owned action.",
    steps: [
      "Add a Webhook node, set the HTTP Method to POST, and use the node's HTTPS test URL while building the workflow.",
      "Listen for a test event, then send a workflow-ready opportunity from Opportunity Scanner to the test URL.",
      "Add a Switch node using {{$json.opportunity.revenueMotion}}. Create routes such as Sell to Agency, Sell to Funded Buyer, and Partner with Recipient.",
      "On each route, add the appropriate CRM, project, email, or messaging node. Reference nested values with expressions such as {{$json.opportunity.nextBestAction}}.",
      "Configure the Webhook node to respond immediately or otherwise return a successful 2xx response within eight seconds.",
      "Activate the workflow and replace the test URL in Opportunity Scanner with n8n's HTTPS production URL for future sends."
    ],
    mapping: [
      ["Switch value", "{{$json.opportunity.revenueMotion}}"],
      ["Account", "{{$json.opportunity.targetAccount}}"],
      ["Record title", "{{$json.opportunity.opportunity}}"],
      ["CRM note", "{{$json.opportunity.crmNote}}"],
      ["Task", "{{$json.opportunity.nextBestAction}}"],
      ["Evidence link", "{{$json.opportunity.sourceUrl}}"]
    ]
  }
];

const errorRows = [
  ["400", "Invalid request", "The webhook URL is missing, is not HTTPS, includes embedded credentials, or the scan/opportunity IDs are missing."],
  ["403", "Full report required", "Sending to workflow is available only for a full report."],
  ["404", "Record not found", "The scan or opportunity no longer matches a stored record."],
  ["413", "Payload too large", "The opportunity object exceeds 25,000 bytes."],
  ["422", "Not workflow ready", "A required field is empty or the opportunity needs more research."],
  ["502", "Delivery failed", "The destination rejected the request with a non-2xx response or could not be reached."],
  ["504", "Delivery timed out", "The destination did not accept the request within eight seconds."]
];

function CodeBlock({ children }: { children: string }) {
  return (
    <pre className="overflow-x-auto rounded-lg border border-slate-700 bg-ink p-4 text-xs leading-6 text-slate-100 shadow-sm" tabIndex={0}>
      <code>{children}</code>
    </pre>
  );
}

function SectionHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) {
  return (
    <div>
      <p className="text-xs font-semibold uppercase tracking-wide text-accent">{eyebrow}</p>
      <h2 className="mt-2 text-2xl font-semibold text-ink">{title}</h2>
      {children ? <div className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{children}</div> : null}
    </div>
  );
}

export default function WebhookDocumentationPage() {
  return (
    <main className="min-h-screen bg-field">
      <SiteHeader
        rightSlot={
          <a href="/#scan" className="rounded-md bg-accent px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-[#0A6871]">
            Run Free Scan
          </a>
        }
      />

      <section className="border-b border-line bg-white">
        <div className="mx-auto max-w-7xl px-6 py-12 lg:py-14">
          <Badge tone="blue">Integration documentation</Badge>
          <h1 className="mt-5 max-w-4xl text-4xl font-semibold leading-tight text-ink sm:text-5xl">
            Send opportunity rows into the tools your team already uses.
          </h1>
          <p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">
            Each send delivers one workflow-ready opportunity as JSON to a Zapier, Make, n8n, or custom HTTPS webhook. This reference covers the current payload, delivery rules, and practical setup recipes.
          </p>
          <nav aria-label="On this page" className="mt-8 flex flex-wrap gap-2 text-sm font-semibold">
            {[
              ["Quick start", "#quick-start"],
              ["Payload", "#payload"],
              ["Field reference", "#fields"],
              ["Recipes", "#recipes"],
              ["Delivery rules", "#delivery"]
            ].map(([label, href]) => (
              <a key={href} href={href} className="rounded-md border border-line bg-field px-3 py-2 text-steel hover:border-accent hover:text-accent">
                {label}
              </a>
            ))}
          </nav>
        </div>
      </section>

      <section id="quick-start" className="scroll-mt-24 border-b border-line bg-field">
        <div className="mx-auto max-w-7xl px-6 py-12">
          <SectionHeading eyebrow="Quick start" title="Connect a webhook in four steps">
            <p>No API key or custom request code is needed for the standard in-product flow.</p>
          </SectionHeading>
          <ol className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            {[
              ["1", "Create the trigger", "Create a catch-hook or webhook trigger in your destination tool and copy its HTTPS URL."],
              ["2", "Open a full report", "Choose a row marked Workflow ready, then select Send to Workflow."],
              ["3", "Send a sample", "Paste the webhook URL and send. The destination uses this event to discover the fields."],
              ["4", "Map and verify", "Map the opportunity fields, activate the automation, and send another row to test the live path."]
            ].map(([number, heading, copy]) => (
              <li key={number} className="border-l-4 border-accent bg-white p-5 shadow-sm">
                <span className="text-sm font-semibold text-accent">Step {number}</span>
                <h3 className="mt-2 text-base font-semibold text-ink">{heading}</h3>
                <p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      <section id="payload" className="scroll-mt-24 border-b border-line bg-white">
        <div className="mx-auto grid max-w-7xl gap-8 px-6 py-12 lg:grid-cols-[0.78fr_1.22fr]">
          <div>
            <SectionHeading eyebrow="Payload" title="Delivery envelope">
              <p>The webhook receives an HTTP POST with <code className="font-semibold text-ink">Content-Type: application/json</code>.</p>
            </SectionHeading>
            <dl className="mt-6 grid gap-3 text-sm">
              <div className="border-l-2 border-line pl-4">
                <dt className="font-mono font-semibold text-ink">product</dt>
                <dd className="mt-1 leading-6 text-slate-600">String. Always <code>Opportunity Scanner</code>.</dd>
              </div>
              <div className="border-l-2 border-line pl-4">
                <dt className="font-mono font-semibold text-ink">sent_at</dt>
                <dd className="mt-1 leading-6 text-slate-600">String. ISO 8601 timestamp created when delivery begins.</dd>
              </div>
              <div className="border-l-2 border-line pl-4">
                <dt className="font-mono font-semibold text-ink">opportunity</dt>
                <dd className="mt-1 leading-6 text-slate-600">Object. The server-generated opportunity record described below.</dd>
              </div>
            </dl>
            <div className="mt-6 rounded-md border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">
              Optional properties with no value are omitted from the JSON. Build mappings that tolerate missing optional fields.
            </div>
          </div>
          <CodeBlock>{samplePayload}</CodeBlock>
        </div>
      </section>

      <section id="fields" className="scroll-mt-24 border-b border-line bg-field">
        <div className="mx-auto max-w-7xl px-6 py-12">
          <SectionHeading eyebrow="Field reference" title="Opportunity object">
            <p>&quot;Required&quot; means the server will not attempt delivery without a usable value. &quot;Conditional&quot; means one of the two target fields must be present.</p>
          </SectionHeading>
          <div className="mt-6 overflow-x-auto rounded-lg border border-line bg-white shadow-sm">
            <table className="w-full min-w-[820px] border-collapse text-left text-sm">
              <thead className="bg-ink text-xs uppercase tracking-wide text-slate-200">
                <tr>
                  <th className="px-4 py-3 font-semibold">Field</th>
                  <th className="px-4 py-3 font-semibold">JSON type</th>
                  <th className="px-4 py-3 font-semibold">Delivery</th>
                  <th className="px-4 py-3 font-semibold">Meaning</th>
                </tr>
              </thead>
              <tbody>
                {fields.map((field) => (
                  <tr key={field.name} className="border-b border-line last:border-b-0 align-top">
                    <td className="px-4 py-3 font-mono text-xs font-semibold text-ink">{field.name}</td>
                    <td className="px-4 py-3 font-mono text-xs text-steel">{field.type}</td>
                    <td className="px-4 py-3">
                      <span className={`inline-flex rounded-md border px-2 py-1 text-xs font-semibold ${field.delivery === "Required" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : field.delivery === "Conditional" ? "border-amber-200 bg-amber-50 text-amber-800" : "border-line bg-field text-slate-600"}`}>
                        {field.delivery}
                      </span>
                    </td>
                    <td className="max-w-xl px-4 py-3 leading-6 text-slate-600">{field.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section id="recipes" className="scroll-mt-24 border-b border-line bg-white">
        <div className="mx-auto max-w-7xl px-6 py-12">
          <SectionHeading eyebrow="Recipes" title="Zapier, Make, and n8n setup" />
          <div className="mt-7 grid gap-10">
            {recipes.map((recipe) => (
              <article key={recipe.name} className="grid gap-6 border-t border-line pt-8 first:border-t-0 first:pt-0 lg:grid-cols-[0.72fr_1.28fr]">
                <div>
                  <Badge tone="green">{recipe.name}</Badge>
                  <h3 className="mt-4 text-xl font-semibold text-ink">{recipe.purpose}</h3>
                  <div className="mt-5 overflow-hidden rounded-md border border-line">
                    <table className="w-full text-left text-xs">
                      <thead className="bg-field text-slate-500">
                        <tr>
                          <th className="px-3 py-2 font-semibold">Destination field</th>
                          <th className="px-3 py-2 font-semibold">Payload value</th>
                        </tr>
                      </thead>
                      <tbody>
                        {recipe.mapping.map(([destination, value]) => (
                          <tr key={destination} className="border-t border-line align-top">
                            <td className="px-3 py-2 font-semibold text-ink">{destination}</td>
                            <td className="break-all px-3 py-2 font-mono text-steel">{value}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
                <ol className="grid gap-3">
                  {recipe.steps.map((step, index) => (
                    <li key={step} className="grid grid-cols-[2rem_1fr] gap-3 text-sm leading-6 text-slate-600">
                      <span className="grid h-8 w-8 place-items-center rounded-md bg-mist font-semibold text-accent">{index + 1}</span>
                      <span className="pt-1">{step}</span>
                    </li>
                  ))}
                </ol>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section id="delivery" className="scroll-mt-24 bg-field">
        <div className="mx-auto max-w-7xl px-6 py-12">
          <SectionHeading eyebrow="Delivery rules" title="What your endpoint must do">
            <p>These limits apply to the current webhook sender.</p>
          </SectionHeading>
          <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            {[
              ["HTTPS only", "The destination URL must use HTTPS and cannot contain embedded username/password credentials."],
              ["Return 2xx", "Any non-2xx destination response is treated as a failed delivery."],
              ["Eight seconds", "The destination must accept the request within eight seconds."],
              ["One attempt", "Opportunity Scanner does not currently retry a failed webhook automatically. Send the row again after correcting the issue."]
            ].map(([heading, copy]) => (
              <div key={heading} className="border-t-4 border-ink bg-white p-5 shadow-sm">
                <h3 className="text-base font-semibold text-ink">{heading}</h3>
                <p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p>
              </div>
            ))}
          </div>

          <h3 className="mt-10 text-lg font-semibold text-ink">Errors shown in Opportunity Scanner</h3>
          <div className="mt-4 overflow-x-auto rounded-lg border border-line bg-white">
            <table className="w-full min-w-[720px] text-left text-sm">
              <thead className="bg-field text-xs uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-4 py-3 font-semibold">Status</th>
                  <th className="px-4 py-3 font-semibold">Meaning</th>
                  <th className="px-4 py-3 font-semibold">What to check</th>
                </tr>
              </thead>
              <tbody>
                {errorRows.map(([status, meaning, detail]) => (
                  <tr key={status} className="border-t border-line align-top">
                    <td className="px-4 py-3 font-mono font-semibold text-ink">{status}</td>
                    <td className="px-4 py-3 font-semibold text-ink">{meaning}</td>
                    <td className="px-4 py-3 leading-6 text-slate-600">{detail}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="mt-8 border-l-4 border-review bg-white p-5 text-sm leading-6 text-slate-600 shadow-sm">
            <h3 className="font-semibold text-ink">Operational note</h3>
            <p className="mt-2">Webhook requests are server-generated from the stored scan and opportunity. The current sender does not add a signature or authorization header, so treat the destination URL as a secret, use the access controls offered by your automation platform, and avoid logging the full URL.</p>
            <p className="mt-2">Always recheck the live source before outreach, submission, or a deadline-sensitive action. The webhook moves research into workflow; it does not replace source verification.</p>
          </div>
        </div>
      </section>

      <SiteFooter />
    </main>
  );
}
